### ISSUE TITLE
Housekeeping recommendations

### ISSUE THREAD

**Issue by oncletom** [kaelig/moniteur#4]
Here are some recommendations:
- [x]  bin/www should rather be ./server.js  (and called as `moniteur --config ... start`)
- [x] lib/index.js should rather be /bin/moniteur (and called as `moniteur --config ... save`)
- [x] lib/read.js should rather be /bin/moniteur (and called as `moniteur --config ... read`)
- [ ] cli read/save can have an HTTP counterpart (like `/api/data-points`, GET to read and POST to save)
- [ ] the web interface could be a subdependency (`moniteur-www`) and served only on demand (`moniteur --config ... start --with-ui`)
- [x] package.json should have a [bin](https://www.npmjs.org/doc/files/package.json.html#bin) property aiming at `bin/moniteur` so as `npm install --global moniteur` would make the command globally available to the system)

Alerts and stuff should be baked outside of this module, and should access the API/listen to webhooks in order to email/notifify. Something like `moniteur-notifier`.

**Comment by kaelig** [comment]
Closing this as it's been evolving quite a lot.
